apiVersion: v1
kind: Service
metadata:
  name: library
  labels:
    app: library
    service: library
spec:
  ports:
    - port: 9000
      name: http
  selector:
    app: library
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: library
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  labels:
    app: library
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library
      version: v1
  template:
    metadata:
      labels:
        app: library
        version: v1
    spec:
      serviceAccountName: library
      containers:
        - name: library
          image: docker.io/bazzo03/library-api:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---